# Generated by Django 5.2.4 on 2026-04-12 19:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individuals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='individualtransaction',
            options={'ordering': ['-date', '-created_at']},
        ),
        migrations.AddField(
            model_name='individualtransaction',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='individualbudget',
            name='monthly_budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='individualtransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='individualtransaction',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='individualtransaction',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='individualtransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ind_transactions', to=settings.AUTH_USER_MODEL),
        ),
    ]
