# Generated by Django 5.2.4 on 2026-04-29 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('individuals', '0002_alter_individualtransaction_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individualtransaction',
            name='category',
        ),
    ]
