# Generated by Django 5.2.4 on 2026-04-29 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyBudgetHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('allocated', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_expense', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_income', models.DecimalField(decimal_places=2, max_digits=12)),
                ('saved', models.DecimalField(decimal_places=2, max_digits=12)),
                ('carried_over', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_history', to='department.department')),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('department', 'year', 'month')},
            },
        ),
        migrations.DeleteModel(
            name='BudgetRequest',
        ),
    ]
